# Generated by Django 4.1.7 on 2023-04-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '__first__'),
        ('buyer_details', '__first__'),
        ('seller_details', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reed', models.CharField(max_length=150)),
                ('pik', models.CharField(max_length=150)),
                ('width', models.CharField(max_length=150)),
                ('pcs', models.CharField(max_length=150)),
                ('discount', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=150)),
                ('delivery_period', models.DateField()),
                ('payment_terms', models.CharField(max_length=150)),
                ('transport', models.CharField(max_length=150)),
                ('delivery_at', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=150)),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.quality')),
                ('agentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('buyername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_details.buyer')),
                ('sellername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_details.seller')),
            ],
        ),
    ]
