# Generated by Django 4.1.7 on 2023-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
