# Generated by Django 4.1.7 on 2024-01-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        ('form', '0003_alter_form_delivery_at_alter_form_delivery_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
        ),
    ]
